name: Backup Smart Classroom Data

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and publish
      env:
        ENDPOINT: ${{ secrets.ORACLE_ENDPOINT }}
        USERNAME: ${{ secrets.ORACLE_USERNAME }}
        PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
      run: |
        python main.py --username="$USERNAME" --password="$PASSWORD" --endpoint="$ENDPOINT"
    - name: Commit new backup version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate new backup
        file_pattern: data/